Song.create(title: 'Cant Touch This', artist: 'MC Hammer', price: 0.99, duration: 60)
Song.create(title: 'Wrong Way', artist: 'Sublime', price: 0.99, duration: 120)
Song.create(title: 'Cant Fight This Feeling', artist: 'Journey', price: 0.99, duration: 80)
Song.create(title: 'Im Too Sexy', artist: 'Right Said Fred', price: 0.99, duration: 70)
Song.create(title: 'Bohemian Rhapsody', artist: 'Queen', price: 0.99, duration: 45)
Song.create(title: 'Black Hole Sun', artist: 'Soundgarden', price: 0.99, duration: 120)
Song.create(title: 'Jeremy', artist: 'Pearl Jam', price: 0.99, duration: 100)
Song.create(title: 'Plowed', artist: 'Sponge', price: 0.99, duration: 110)
Song.create(title: 'Faith', artist: 'George Michaels', price: 0.99, duration: 140)
Song.create(title: 'Stairway to Heaven', artist: 'Led Zeppelin', price: 0.99, duration: 300)
